### ISSUE TITLE
vit3.0 vue 打包报错

### ISSUE THREAD

**Issue by tulingwb** [JaimeCheng/vue-esign#22]
项目能够正常运行，但是在打包的时候报错
'openBlock' is not exported by node_modules/vue-esign/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vue-esign/src/index.vue
file: D:/work/test/datagovern-ui/node_modules/vue-esign/src/index.vue:278:9
276: }
277:
278: import { openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
              ^
279:
280: function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
error during build:
Error: 'openBlock' is not exported by node_modules/vue-esign/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vue-esign/src/index.vue
    at error (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
    at Module.traceVariable (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:12771:29)
    at ModuleScope.findVariable (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:11423:39)
    at FunctionScope.findVariable (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at ChildScope.findVariable (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:6355:38)    at Identifier.bind (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:7422:40)
    at CallExpression.bind (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at CallExpression.bind (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:8918:15)
    at SequenceExpression.bind (file:///D:/work/test/datagovern-ui/node_modules/rollup/dist/es/shared/rollup.js:5248:73)

**Comment by zhyebe** [comment]
我的是报错，vite+vue3

**Comment by wphubs** [comment]
兄弟们解决了吗，我也是报错 'openBlock' is not exported by node_modules

**Comment by 18502123053** [comment]
兄弟们 解决了吗 vite+vue3  'openBlock' is not exported by node_modules

**Comment by D1god** [comment]
`resolve: { dedupe: ['vue'] }` in `vite.config.js` shall solve the problem.
